### ISSUE TITLE
Disk Eject showing garbage when no disk image mounted

### ISSUE THREAD

**Issue by drencorxeen** [VCCE/VCC#12]
I downloaded the 2.01b today on my main Windows 10 Home (1511) system and found that I am getting garbage on the Disk Eject where it should be saying Empty.  Not sure if this is because of Windows 10 or possibly another issue.

![2015-11-18 4](https://cloud.githubusercontent.com/assets/14010507/11262675/9af6cdac-8e47-11e5-97cd-3aa1b1b37374.png)

**Comment by ursine** [comment]
I suspected this could be caused by the Drive[X].ImageName not being initialized, however, on the startup of the fd502 module each of the disks is "unmounted" by calling unmount_disk_image(X).  This clears the text for the eject string.  I'll need to do some more digging around.

**Comment by BGPierce** [comment]
Gary, while playing around with my local copy, I got this fixed by just intializing an "Empty" string in the init section of the FD502 code when VCC starts. The "ini" file will over ride it if any disks are already mounted.

This fixed the issue, but I did not commit it as I was playing around with other stuff and screwed it all up eventually :-(
I couldn't seem to get this method to work with the SuperIDE module, but you may have better luck.

 

 


Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull

 

My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page
Global Moderator for TRS-80/Tandy Color Computer Forums
http://www.tandycoco.com/forum/

E-Mail: ooogalapasooo@aol.com


 

 

-----Original Message-----

**Comment by ursine** [comment]
It looks like that is what the current code is doing.  I was unable to replicate this on my system.  I'll take another look at it later when I have a chance.

**Comment by BGPierce** [comment]
I just compiled the latest merges and it seems this has disappeared. The drive slot is just showing a blank when no disk is mounted.
This is on Win Vista, I will test on XP and Win8 to make sure.

**Comment by ursine** [comment]
I am seeing this on the "HD Drive 0" menu presently.  I'll take a look at it shortly.  I have not seen it on the floppy, though.

**Comment by BGPierce** [comment]
I think Joe fixed the floppy dialog on the very last upload he did. The garbage is in the dialogs in the harddrive.dll, and the superIDE.dll. I think that would have them all covered.
Then we can completely close this issue :-)

 

 


Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull

 

My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page
Global Moderator for TRS-80/Tandy Color Computer Forums
http://www.tandycoco.com/forum/

E-Mail: ooogalapasooo@aol.com


 

 

-----Original Message-----

**Comment by ursine** [comment]
That last merge should cover both the harddrive and superide.

**Comment by ursine** [comment]
This should be closable with the coming release.
