### ISSUE TITLE
Orcestra-90 pak has no rom

### ISSUE THREAD

**Issue by BGPierce** [VCCE/VCC#2]
Being an avid user of the Orchestra-90, I decided to test it in the Vcc 2.00 build only to be brought to the "Extended Basic" prompt after setting the MPI switch to Orch90 and resetting the emulator.
Being curious, I viewed the orch90 source and saw the rom had been removed, but no provision made for loading the rom as there is with the FD-502 controller.

The Orch-90 pak still works as a stereo Coco sound source, just not as a "rompak" since there is no rom.

Solution? Add a rom loader to the Orch90.dll and store the rom in the Vcc install folder like all other system roms. The rom is readilly available in all the archives.

By the way... I have full permission (in email form) from Jon Bokleman (orch90 author) and Bryan Eggars (owner Software Affair) to use their Orch-90 code in any way I please, though I think the copyrights still belong to Tandy.

**Comment by vcc6809** [comment]
Really, had no idea anyone was using that. Sure ill fix it. 

On Aug 28, 2015, at 6:12 PM, Bill Pierce <notifications@github.com> wrote:

Being an avid user of the Orchestra-90, I decided to test it in the Vcc 2.00 build only to be brought to the "Extended Basic" prompt after setting the MPI switch to Orch90 and resetting the emulator.
Being curious, I viewed the orch90 source and saw the rom had been removed, but no provision made for loading the rom as there is with the FD-502 controller.

The Orch-90 pak still works as a stereo Coco sound source, just not as a "rompak" since there is no rom.

Solution? Add a rom loader to the Orch90.dll and store the rom in the Vcc install folder like all other system roms. The rom is readilly available in all the archives.

By the way... I have full permission (in email form) from Jon Bokleman (orch90 author) and Bryan Eggars (owner Software Affair) to use their Orch-90 code in any way I please, though I think the copyrights still belong to Tandy.
