### ISSUE TITLE
Please add build instructions to the sources

### ISSUE THREAD

**Issue by ReddyKilowatt** [VCCE/VCC#58]
Which version(s) of Visual Studio are required to build VCC?

**Comment by BGPierce** [comment]
Visual Studio 2015 Community
It's a free download from MSDN
You must be sure to get the Win32 & WinXP compatibility packages
The master branch is under developement and will not run correctly, so use the "VCC-1.200b" branch as that is the current release.

**Comment by ReddyKilowatt** [comment]
I know, but this information needs to be in readme file that is included
with the sources.

**Comment by BGPierce** [comment]
Actually, I like that idea.... imaginge that... software with instructions? It's an outlandish thought, but I like it!
Thanks for the suggestion. I will see what I can do. I will also add a build page to the wiki.

**Comment by BGPierce** [comment]
Done

**Comment by ReddyKilowatt** [comment]
Outlandish? Why?

Sarcasm?


Thanks

**Comment by BGPierce** [comment]
Actually, more like bad humor. We had a discussion on this on the Coco Mail List a while back, and that was a stab at that conversation. We had a lot of "I wrote the program, why should I write the manul" attitudes.
I try to have at least text instructions for every thing I do, if not a complete manual. In this case, I hadn't even thought of anyone actually trying to compile VCC so I hadn't included instructions. We set up this site to develope VCC, not for downloading the source, though people are welcome to do so. We are building and distributing the VCC exec, not trying to distribute the source. That's why there's a manual included in the VCC exec download package. 

 

 


Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull

 

My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page
Global Moderator for TRS-80/Tandy Color Computer Forums
http://www.tandycoco.com/forum/

E-Mail: ooogalapasooo@aol.com


 

 

-----Original Message-----

**Comment by ReddyKilowatt** [comment]
I wasn't suggesting to write a manual, just a 1 line readme file stating
which version of Visual Studio to use.
The project file should contain the necessary settings.

I would shave done the pull request myself to do that, but didn't know if
my addition would be implemented or tossed out.

**Comment by ReddyKilowatt** [comment]
>>We are building and distributing the VCC exec, not trying to distribute
the source.
If that's the case then only the developers should have access, not the
public.

I didn't realize this. You can use BiBucket to make to a private Git repo,
and just add a few developers to the project.
Another public repo can be setup for the exe download package.

**Comment by BGPierce** [comment]
We actually want the public to have access, if they want to compile it. But to be honest, I have seen very little interest in it. If someone can compile it, and add features, then we welcome the contributions and will try to use it. But at the moment, the master branch is being converted in phases to a new layout and could completely change by the time someone gets anything usable to add.
The "VCC-1.200b" branch is the current "release" and is buildable and runs, but to add changes to that would be adding to old code as the master is WAY ahead of it, but incomplete.
If you're ineterested in joining in, send me a private email and it can be discussed :-) 
 

 


Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull

 

My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page
Global Moderator for TRS-80/Tandy Color Computer Forums
http://www.tandycoco.com/forum/

E-Mail: ooogalapasooo@aol.com


 

 

-----Original Message-----

**Comment by ReddyKilowatt** [comment]
>>If you're ineterested in joining in, send me a private email and it can
be discussed :-)
If I had the time and more experience, I'd love to.

I'm not up on the Coco3's architecture & memory map enough to try to help,
and I'm definitely a noob with the 6809 instructions.

I'm curious as to how he reverse engineered the GIME, though. I don't
follow the list regularly, so if it had already been reverse engineered and
documented, that's a great place to start.

Emulation has always been a mystery to me. I understand how the instruction
fetch/execute loop works, but when it comes to creating the video and other
hardware it's all a mystery.

Mr Forgione did d a great job and I'm so glad that he made the source
available.

>> But to be honest, I have seen very little interest in it.
I'm sure there will be some momentum overtime. I wouldn't be too concerned
that you're not getting a flood of interest from developers. It will happen.
