### ISSUE TITLE
create floppy images

### ISSUE THREAD

**Issue by ghendric** [VCCE/VCC#6]
Can this emulator create floppy images from actually floppies from OS9 and RSDOS disks?

**Comment by BGPierce** [comment]
At one time it could. The feature is still there, but to be honest, I don't have old enough hardware to test it.
You need an old enough computer to have the floppy disk chip set to support 720k, 256 byte sectors and a bios option to set it as such.
Then you need the floppy driver described in the VCC manual, and I don't think the site exists anymore as well as the author's email is invalid and you can't verify the license (free).
It's been a long time since I heard of anyone getting this to work and that was with Joseph's old version.


-----Original Message-----
