### ISSUE TITLE
Cannot make DriveWire connection work

### ISSUE THREAD

**Issue by BrianHoldsworth** [VCCE/VCC#61]
I have tried various DW ROM images and also just using "becker.dll", and I'm unable to access any DW mounted disks. It is possible I am just doing something wrong, but I have tried the most trivial use case I can think of:

1. Configure DW4 for TCP/IP, Becker Port instance.
2. Mount a simple 156K Coco .dsk image file in DW4,
3. Insert "becker.dll" directly into the cartridge slot.
4. Ensure DriveWire settings in Vcc are set to 127.0.0.1/65004.
5. Hard reset the emulator and type "DIR1", "DRIVE1", etc. commands.

All I ever get is syntax errors. It seems like there is no ROM image loaded that know how to access DriveWire, BUT I DO see a client connection gets established to the DW4 server.

I have also tried many other configurations using DW compatible ROM images, but to no avail. I have no way of configuring the server address/port when using the ROM images, but I do also see client connections being established to my DW4 server. With the ROM images, I never get a prompt. Vcc just hangs after displaying the HDB-DOS banner.

Please advise...

**Comment by beretta42** [comment]
Just a thought:  Did you try to put becker.dll and a hdbdos ROM in the
virtual MPI ?  Inserting either directly into the cart port will probably
mutually exclude the other.  The coco software -or- the hardware, but not
both.

--brett


On Sun, Jul 24, 2016 at 10:15 PM, Brian Holdsworth <notifications@github.com

**Comment by BGPierce** [comment]
First of all, VCC & the Becker.dll do NOT use the "dw" named roms or disks of any type... this being roms, waves, bins, nitros9 boot disks etc.That's why it's called the "becker port" and not "drivewire port".Yes, there needs to be better documentation for all this stuff, and what little there is, is hard to find. The becker port uses unused port addresses on the Vcc emulator (and CocoFPGA for which it was developed) to connect to a TCP socket on the host computer, therefore emulating the serial connection. DW roms are strictly serial (COco bit banger port) and cannot be used with Vcc and the becker port.To use Dw4 & the becker port in VCC, you must use roms, waves, bins, Nitros9 boot disks, etc, labeled with "becker", "bc3", or "bck". Various forms of becker related soms and software will use one of those name extensions.Also, if you read the VCC manual, you will find "SPECIFIC" instructions on how to use the becker port and the various roms supplied with VCC. The manual isn't laid out the best in the world, but the info's there,Bill Pierce"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/Co-Contributor, Co-Editor for CocoPediahttp://www.cocopedia.com/wiki/index.php/Main_PageGlobal Moderator for TRS-80/Tandy Color Computer Forumshttp://www.tandycoco.com/forum/E-Mail: ooogalapasooo@aol.com-----Original Message-----From: Brett M. Gordon <notifications@github.com>To: VCCE/VCC <VCC@noreply.github.com>Sent: Sun, Jul 24, 2016 10:28 pmSubject: Re: [VCCE/VCC] Cannot make DriveWire connection work (#61)

Just a thought:  Did you try to put becker.dll and a hdbdos ROM in the
virtual MPI ?  Inserting either directly into the cart port will probably
mutually exclude the other.  The coco software -or- the hardware, but not
both.

--brett


On Sun, Jul 24, 2016 at 10:15 PM, Brian Holdsworth <notifications@github.com

**Comment by BrianHoldsworth** [comment]
Thank you for the help! This is obviously not an issue.

My misunderstanding was in thinking that "becker.dll" was providing a ROM image on the Coco for DW access. My modified "trivial" method to get DW access to work from Vcc is now as below, and this method DOES work.

1. Configure DW4 for TCP/IP, Becker Port instance.
2. Mount a simple 156K Coco .dsk image file in DW4,
3. Insert "mpi.dll" into the cartridge slot, a DW capable ROM in slot 1, and "becker.dll" in slot 2.
4. Select MPI slot 1 as active.
5. Ensure DriveWire settings in Vcc are set to 127.0.0.1/65004.
6. Hard reset the emulator, and the DW mounted disk should be accessible.

**Comment by BGPierce** [comment]
Again, read the manual...
There is a place in the "FD-502 Config" in which to use "external" roms for the FD-502. You do not need to use up an MPI slot.
There are 5 alternate roms supplied with Vcc (found in the vcc install folder):
"hdbdw3bk3.rom" - standard HDBDOS rom with becker access
"hdbdw3bk3 w-offset 5A000.rom" - for use with "dual partitioned" VHDs configured for RSDOS & OS9
The next 2 are the same as above, but do not run in 2mhz mode (the above do) for timing of games and such:
"hdbdw3bck.rom"
"hdbdw3bck w-offset 5A000.rom"
The next is for use with the superide.dll (another story altogether)
"hdblba.rom"

All other roms are loaded dynamically (coco3.rom, rgbdos.rom, disk11.rom, orch90.rom) when needed or set in FD-502 config (i.e. disk11.rom & rgbdos.rom)

Typically, in using dw4 with Vcc, you would use one of the first 4 according to your needs. Mainly dependant on whether you're using NitrOS9 and dual partitioned VHDs. In trying to load regular RSDOS disk images (as you seem to be doing), the "non-offset" roms would be used (i.e. hdbdw3bc3.rom & hdbdw3bck.rom).

A typical dw4/Vcc setup would be:
Cartridge: mpi.dll
MPI Slot 4: fd502.dll
MPI Slot 3: harddrive.dll (only accessable with RGBDOS or "emudsk" drivers in OS9)
MPI Slot 2: becker.dll (default settings)
MPI Slot 1: orch90.dll
MPI Slot Switch set to "4"
FD502 Config: Check "External Rom Image" and load the rom of your choice.

With this setup, you have access to most things.

There are many configurations possible, so it gets a little confusing some times. I hope to get the time in the future to rewrite the manual with better instructions and a better layout. The current manual was just an edit to Joe's original manual in attempt to include the new info and get the release out as quick as possible.
Info for using hdbdos is in the hdbdos manual on Cloud9's website.

Another thing handy to know is that in win 7 and higher, you need to set Vcc to run in "Administrator Mode". If you don't, your "vcc.ini" will not be saved and you lose all your settings each time you run it.

 

 


Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull

 

My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page
Global Moderator for TRS-80/Tandy Color Computer Forums
http://www.tandycoco.com/forum/

E-Mail: ooogalapasooo@aol.com


 

 

-----Original Message-----
