### ISSUE TITLE
DIVQ / OpCode 118E 6309 not implemented

### ISSUE THREAD

**Issue by drencorxeen** [VCCE/VCC#73]
Just thought I would make a issue post about the DIVQ / OpCode 118E 6309 not being emulated in the sources yet.

I went through hd6309.c and found that the case statement is there for it, but hasn't been implemented to actually work yet.

**Comment by abathur8bit** [comment]
Now fixed in commit b629dcbe03c85df1fa5c94e95d7e301ba7647cb. DIVQ is implemented for all addressing modes, and tested in RSDOS and Nitros9 6309 EOU Alpha 3. BASIC09 was previously unable to divide two integer values. They can now. 

Before fix, you can see the result of 20/10 is 0. Clearly wrong. 
![screen_shot_2018-03-14_at_1 59 53_am](https://user-images.githubusercontent.com/24625148/37618018-2160383c-2b8b-11e8-9bd5-bb83cc4e28de.png)

After fix, the correct answer of 2 is displayed:
![screen_shot_2018-03-14_at_5 55 24_pm](https://user-images.githubusercontent.com/24625148/37618056-3a3178ee-2b8b-11e8-9f6d-9f32a532b861.png)
