### ISSUE TITLE
Creating Back Buffer in System RAM! This will be slower

### ISSUE THREAD

**Issue by ogsteviestrow** [VCCE/VCC#74]
My VCC now has this error message every time I launch it, "Creating Back Buffer in System RAM! This will be slower" This started after David Ladd showed me how to connect VCC to DriveWire 4.

I thought I could undo the settings, but no good. I tried to remove the program, and even install in a different directory, still same issue.

The main problem with this error message is that I can't run VCC on my 2nd display, which is to the left of the primary, it freezes up on that display, which is a problem for me since I have a special set up for recording my youtube videos.

Anyway, my recording issues aren't as important as understanding what's causing this and hopefully fixing it, as it may affect someone else in the future.

Thanks!

**Comment by BGPierce** [comment]
Steve, If I remember correctly, this an issue with DirectX, hence why it's using ram.
I'm really not sure. I ran into this issue at one point and fixed it, but I don't remember what it was. I do remember it was windows and not VCC. I'm not sure what setting up DW4 would have to do with it as that has nothing to do with video.

 

 

Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull

My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page

E-Mail: ooogalapasooo@aol.com

 

 

-----Original Message-----

**Comment by ogsteviestrow** [comment]
Ron Klein also suggested it may have something to do with my graphics driver or settings, or Direct X.
I tried resetting all my my drivers settings, I do have the latest driver for NVIDIA.
David Ladd suggested a forced re-install of the Direct X run-time, which I also did, and that didn't solve my problem.
There is something odd going on in my desktop, because this issue doesn't happen on my laptop, and I'm running the same EXE file and INI file from a shared Google Drive.

FWIW, this issue was also reported in VCC 1.42 back in 2003:
http://thread.gmane.org/gmane.comp.hardware.tandy.coco/70434

So I'm not the only one who had it, but right now it's just frustrating the heck out of me.

**Comment by BGPierce** [comment]
Steve, the more I think about this, the more I think I had this problem right after installing Win10 but before I finished with the Win10 updates. It seemed to disappear after the updates were finished. Also, there's a HUGE difference in Win10 Home and Win10 Pro. There are a ton of things disabled or just not installed in Win10 Home that are default in Win10 Pro. Also, Win10 pro allows you to disable or uninstall all MS's stupid APPS whereas Win10 Home does not, you are stuck with them. Win10 Home is for housewives using FaceBook and bogus coupon sites...
I reverted back to Win7 Pro and haven't messed with Win10 since. I only used it to validate VCC was working correctly then back to Win7 I went. Win10 has so many apps pinging the net for updates, selling your address and phone number, and basically selling you out, that it used up my daily bandwith in less than 30 minutes. Then after disabling all that crap, it still had so much chatter going on in the background that my M-Audio Delta 10/10 8 channel pro audio recording interface would stutter on playback. Since I make my living with this interface, I had to abandon Win10.

 

 

Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull

My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page

E-Mail: ooogalapasooo@aol.com

 

 

-----Original Message-----
