### ISSUE TITLE
Vcc 2.1.0d Welcome manual

### ISSUE THREAD

**Issue by mdavidjohnson** [VCCE/VCC#83]
While upgrading to 2.1.0d , I noticed several typos and other potential problems in the attached pdf file of the Welcome manual. Each such spot is identified by semi-transparent red highlighting along with an associated sticky note. The annotations were placed from within Adobe Acrobat Reader DC, running under Windows 10 Pro.

[Welcome to Vcc 210d Typos.pdf](https://github.com/VCCE/VCC/files/6984865/Welcome.to.Vcc.210d.Typos.pdf)

**Comment by BGPierce** [comment]
Thanks for going through the file so closely. You caught a lot of things I missed. There are "some" things that are as should be, but the typos were spot on. I will be fixing these with the next release (too late for this one LOL).
Thanks again,
Bill P.


-----Original Message-----
From: mdavidjohnson ***@***.***>
To: VCCE/VCC ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Fri, Aug 13, 2021 3:44 pm
Subject: [VCCE/VCC] Vcc 2.1.0d Welcome manual (#83)

While upgrading to 2.1.0d , I noticed several typos and other potential problems in the attached pdf file of the Welcome manual. Each such spot is identified by semi-transparent red highlighting along with an associated sticky note. The annotations were placed from within Adobe Acrobat Reader DC, running under Windows 10 Pro.Welcome to Vcc 210d Typos.pdf—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mdavidjohnson** [comment]
I found some additional possible typos in the keyboard maps on page 37.

 

In the PC Keyboard, VCC Natural (OS-9) Keyboard, and VCC Compact (OS-9) Keyboard:

 

                [0]] should probably be [0)]

 

and in the VCC Coco (DECB) Keyboard:

 

                [9]] should probably be [9)]

 

Also, it might be of some interest to know that, with my Victsing Model PC176B Wireless Keyboard running Windows 10 Pro 64-bit, on the VCC CoCo (DECB) Keyboard, the [Clr} and [Brk] keys don’t seem to do anything. The [home7] key on the number pad returns the same codes as the [Clr] key on the VCC CoCo should, and the [end1] key on the number pad produces the “Break” action. 

 

Also, the [[{] and []}] keys don’t return the characters indicated: the [[{] key returns point codes 8 + 56 + 189 when pressed and 44 (comma) when pressed with the [Shift] key down. The []}] key returns  point codes 9 + 57 + 189 when pressed and 189 + 46 (period) when pressed with the [Shift] key down.

 

--

M. David Johnson

 ***@***.***> ***@***.***

**Comment by BGPierce** [comment]
I'm not sure about the keys you mention, but I have a more recent version I'm uploading soon in which some keyboard issues were fixed. I'm not the one doing the programming and without looking at my notes, I don't remember at the moment what was fixed. I maintain the site, releases and manual.
Also, there is now a custom keymap editor in which you can save your own keymaps, so this may be an option to fix the problem. Some keys got moved around while creating the editor and I think this update fixes that (IIRC).

Thanks again for your input. The new release will be up soon, nothing major, just a few bug fixes.
Bill P.


-----Original Message-----

**Comment by mdavidjohnson** [comment]
Cool!

 

But the four errors (IMHO) I mentioned were errors in the manual, not in the code. The keymaps show a ] closing bracket where they should show a ) closing parenthesis instead.

 

e.g. if you look at the actual “9” key on an actual, physical CoCo, it has a “)” right above the “9”. But the CoCo (DECB) keymap on page 37 of the manual shows a “]” instead.

 

It’s hard to make out with the brackets also being used to indicate the key outlines in the keymaps, but it’s there.

 

--

M. David Johnson

 ***@***.***> ***@***.***

**Comment by ejaquay** [comment]
Regarding keymap editing.    The editor makes no presumptions about what the physical keyboard looks like.  Keyboard editor allows you to add/change mappings by first hitting a key on the physical keyboard.  If the editor sees a single code for that key it can be mapped to a coco key.   Current version allows editing only the custom keymap, this may change in a future release to allow editing any of the four keymaps.   Keymap files can also be edited using notepad but this should not be done while vcc is running.

**Comment by ejaquay** [comment]
Regarding number keypad confusion.  Many early keyboards did not have arrow or home keys.  Instead the number keypad keys were used for up, down, left, right, end, and home depending on the state of the numlock key.   Newer keyboards have a seperate arrow keypad keys that generate different codes that the number keypad does.  To avoid (create?) confusion arrow keypad keys used "expanded codes" which were the same as the corresponding keys on the number pad but with the high order bit set.  The Microsoft API by default masked the high order bit on the expanded codes so existing programs would not have to be changed to use the new arrow keys.    With the keymap editor Vcc 2.1.0d  unmasks these keys so they can be mapped independantly.    Unfortunatly due to an oversight the first Vcc 2.1.0d release did not adjust the default keymappings for the Home and End keys.  A re-release added the correct mappings.   If the Home key is not working as you expect it is because you have the original release and need to download the re-release.

**Comment by BGPierce** [comment]
Ahhhh... gotcha :-)


-----Original Message-----

**Comment by mdavidjohnson** [comment]
Hi Bill -

 

I’ve sent the attached paper to Boisy Pitre in response to his Call for Papers for this year’s CoCoFest.

 

I would appreciate any comments you, or any other members of the VCC Team, might choose to offer.

 

--

M. David Johnson

 ***@***.***> ***@***.***

**Comment by BGPierce** [comment]
I don't see an "attachment"??
Bill P.


-----Original Message-----

**Comment by mdavidjohnson** [comment]
Sorry about that – Here it is.

 

 

--

M. David Johnson

 ***@***.***> ***@***.***

**Comment by BGPierce** [comment]
Apparently, attachments aren't allowed in the "issues". Send it to my email.
Bill P.


-----Original Message-----

**Comment by mdavidjohnson** [comment]
I’d be happy to. Bill –

 

But Outlook doesn’t seem to like your ***@***.*** email address.

 

I’ve never seen that particular obfuscation before – How do I obtain your actual email address out of it?

 

--

M. David Johnson

 ***@***.***> ***@***.***

**Comment by mdavidjohnson** [comment]
Bill – 

 

Were you ever able to recover the copy of the VCC Bundle Paper that I had attached?

 

If not, do you have an alternate email address you’d like me to send it to?

 

--

M. David Johnson

 ***@***.***> ***@***.***

 

I’d be happy to. Bill –

 

But Outlook doesn’t seem to like your ***@***.*** email address.

 

I’ve never seen that particular obfuscation before – How do I obtain your actual email address out of it?

 

--

M. David Johnson

***@***.***

**Comment by BGPierce** [comment]
No, I didn't ever get it, and no, I have no other email. In fact, I've this one for over 30 years


-----Original Message-----

**Comment by mdavidjohnson** [comment]
Hmmmmm ?!?

 

You wrote “Apparently, attachments aren't allowed in the "issues". Send it to my email.”

 

And I responded, “Outlook doesn’t seem to like your ***@***.*** email address.”

 

It seems clear that I’m still living in 1980 and don’t understand how I’m supposed to decipher the ***@***.*** obfuscation.

 

Could you please provide me with a little additional guidance. What am I doing wrong here?

 

--

M. David Johnson

 ***@***.***> ***@***.***

**Comment by BGPierce** [comment]
Personally, I don't see why outlook has a problem with AOL mail. It's one of the oldest surviving email systems since before the internet.
All you should have to do is set an exception for my email in outlook.


-----Original Message-----

**Comment by mdavidjohnson** [comment]
I agree. And I’ve never had any problem with aol emails per se.

 

The difficulty seems to me that the email address is not appearing as:

 

                username at aol dot com

 

Instead, it’s appearing here as:

 

                *** at *** dot ***

 

And I don’t see how to translate the asterisks into a valid aol email address.

 

Along with this email, I’m going to try:

 

                bpierce at aol dot com

 

and

 

                wpierce at aol dot com

 

But I can’t be sure that either one of those is correct.

 

--

M. David Johnson

 ***@***.***> ***@***.***

**Comment by ejaquay** [comment]
I think github is munging the email address.   In any case once email gets
sorted I would appreciate.a copy of the document too.

**Comment by BGPierce** [comment]
Just use ooogalapasooo @ aol . com (remove the spaces and those are lower case os, not zeros)


-----Original Message-----

**Comment by mdavidjohnson** [comment]
Be happy to, Ed –

 

What email address should I use.

 

--

M. David Johnson

 ***@***.***> ***@***.***

**Comment by BGPierce** [comment]
David, I will be closing this "Issue" as I have edited the manual, fixing the typos you mentioned. Before closing, I just wanted to thank you for going through the manual so thoroughly.
Thanks again!
Bill P.
