### ISSUE TITLE
Extended Basic not working with DW4. Boot screen shows loaded. 

### ISSUE THREAD

**Issue by Ralph423** [VCCE/VCC#98]
Drive Wire otherwise works.   

![DW4 bug](https://user-images.githubusercontent.com/77698782/171846133-2ae6bb68-7b51-4b4f-847f-7b77335ecb9b.PNG)

**Comment by BGPierce** [comment]
I just tried it on my system (Win 10) and have no problems. I also downloaded a fresh copy to check if I may have a bad upload, but still no problem.
Try redownloading as you may have gotten a corrupt download. Make sure you overwrite the "coco3.rom" and "hdbdos(xxx).rom" as one of those seems to be your problem. The "WIDTH" command is from "coco3.rom" and has nothing to do with "HDBDOS" so I suspect that's where the problem lies.
Bill P.

**Comment by Ralph423** [comment]
I have becker.dll in slot 4, and hdbdw3bc3.rom in slot 3 with selector set on it.  Don't have a clue what I am doing wrong.  

I am using portable version. 

Went back to this, but no difference
C:\Users\ralph\Desktop\VCC.2.1.0.5.Coco.3.Emulator

Using this because of latest enhancements, and fixes.
C:\Users\ralph\Desktop\VCC.2.1.0.6-beta.Coco.3.Emulator

Ralph

**Comment by Ralph423** [comment]
OOPS!  Didn't mean to close this

**Comment by ejaquay** [comment]
Haven't used drivewire in a while and not near my system to verify but shouldn't fd502.dll, harddrive.dll, and becker.dll be in mpi slots, fd502  selected, with hdbdos(xxx).rom specified as external rom in fd502 config menu?

**Comment by Ralph423** [comment]
That worked !!! Thank you so much.  Have been trying to get this to work many times over the years. 


Ralph
